### ISSUE TITLE
Problem running Spark job on SQL 2019 on AWS

### ISSUE THREAD

**Issue by peterh-cloudiq** [microsoft/sqlworkshops#137]
We have a SQL 2019 BDC cluster on AWS. We are following the tutorial given on https://docs.microsoft.com/en-us/sql/big-data-cluster/tutorial-data-pool-ingest-spark?view=sqlallproducts-allversions. We are failing on the step "Start a spark streaming job". The exception is logged:
2019-09-12 22:51:54,790 ERROR yarn.ApplicationMaster: User class threw exception: org.apache.spark.sql.AnalysisException: Path does not exist: NAMENODE/clickstream_data;
org.apache.spark.sql.AnalysisException: Path does not exist: NAMENODE/clickstream_data;
	at org.apache.spark.sql.execution.datasources.DataSource.sourceSchema(DataSource.scala:225)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo$lzycompute(DataSource.scala:95)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo(DataSource.scala:95)
	at org.apache.spark.sql.execution.streaming.StreamingRelation$.apply(StreamingRelation.scala:33)
	at org.apache.spark.sql.streaming.DataStreamReader.load(DataStreamReader.scala:215)
	at org.apache.spark.sql.streaming.DataStreamReader.load(DataStreamReader.scala:225)
	at FileStreamingBase.StartStreaming(FileStreaming.scala:97)
	at FileStreaming$.main(FileStreaming.scala:204)
	at FileStreaming.main(FileStreaming.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:684)

This, even though the folder clickstream_data is clearly visible in ADS under HDFS on our server, and the file web_clickstreams.csv is in it.

**Comment by BuckWoody** [comment]
Interesting - this is an issues location for the courses themselves, not the product. I would recommend you join the EAP program for support, and of course AWS isn't a supported platform. You would need to contact Amazon for help on their platform.
